apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lossofsignal
  name: lossofsignal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lossofsignal
  template:
    metadata:
      labels:
        app: lossofsignal
      namespace: lossofsignal
      name: lossofsignal
    spec:
      containers:
        - name: lossofsignal
          image: ghcr.io/leemartin77/ld54:a923b33ab6ca77d34200e1ec4ca551f2b8b79728
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - name: http
              containerPort: 80
