apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lossofsignal
  name: lossofsignal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lossofsignal
  template:
    metadata:
      labels:
        app: lossofsignal
      namespace: lossofsignal
      name: lossofsignal
    spec:
      containers:
        - name: lossofsignal
          image: ghcr.io/leemartin77/ld54:4c6c38f2b082c6be9536a4f425266fb1ee4e7760
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 500Mi
          ports:
            - name: http
              containerPort: 80
