apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lossofsignal
  name: lossofsignal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lossofsignal
  template:
    metadata:
      labels:
        app: lossofsignal
      namespace: lossofsignal
      name: lossofsignal
    spec:
      containers:
        - name: lossofsignal
          image: ghcr.io/leemartin77/ld54:9bf5e754d95961eac8df648d3f9564a42b1e1988
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 500Mi
          ports:
            - name: http
              containerPort: 80
