name: Build Project
on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]

  # reference: https://gitlab.com/barichello/godot-ci/-/blob/master/.github/workflows/godot-ci.yml?ref_type=heads

env:
  EXPORT_NAME: LD54
    
jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Web Build
        run: |
          mkdir -v -p build
          docker run --rm -v .:/build docker.io/barichello/godot-ci:mono-3.5.2 /build/build.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: web
          path: build/web
      # - name: Install rsync 📚
      #   run: |
      #     apt-get update && apt-get install -y rsync
      # - name: Deploy to GitHub Pages 🚀
      #   uses: JamesIves/github-pages-deploy-action@releases/v4
      #   with:
      #     branch: gh-pages # The branch the action should deploy to.
      #     folder: build/web # The folder the action should deploy.


  # build-and-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
      # - name: Setup .NET
      #   uses: actions/setup-dotnet@v2
      #   with:
      #       dotnet-version: 6.0.x
      # - name: Cache Godot files
      #   id: cache-godot
      #   uses: actions/cache@v3
      #   with:
      #     path: .godot
      #     key: ${{ runner.os }}-godot
  
      # - name: Generate Prime Numbers
      #   if: steps.cache-godot.outputs.cache-hit != 'true'
      #   run: |
      #     mkdir -p .godot
      #     mkdir -p .godot/godot
      #     mkdir -p .godot/godot-templates
      #     wget --output-document=.godot/godot.zip https://github.com/godotengine/godot/releases/download/3.5.2-stable/Godot_v3.5.2-stable_mono_linux_headless_64.zip
      #     wget --output-document=.godot/godot-templates.tpz https://github.com/godotengine/godot/releases/download/3.5.2-stable/Godot_v3.5.2-stable_mono_export_templates.tpz
      #     unzip .godot/godot.zip -d .godot/godot

      # # .godot/godot/Godot_v3.5.2-stable_mono_linux_headless_64/Godot_v3.5.2-stable_mono_linux_headless.64
      # - name: Export project
      #   run: |
      #     .godot/godot/Godot_v3.5.2-stable_mono_linux_headless_64/Godot_v3.5.2-stable_mono_linux_headless.64 --export HTML5 ./dist